service: iac-aws-localstack

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

functions:
  hello:
    name: iac-aws-localstack-hello
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
